name: "Authorize Backblaze B2 CLI"
description: "Github actions for installing and authorizing Backblaze B2 CLI on Linux"
author: andromidasj
branding:
  icon: terminal
  color: red

inputs:
  version:
    description: "The b2 cli version to download (if necessary) and use. Example: 4.1.0"
    required: false
    default: "latest"

outputs:
  version:
    description: "The Backblaze B2 CLI version that was installed"
    value: ${{ steps.set-output.outputs.version }}

runs:
  using: composite
  steps:
    - id: installing-specific-b2-version
      if: inputs.version != 'latest'
      shell: bash
      run: |
        wget -O /usr/local/bin/b2 https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v${{ inputs.version }}/b2-linux

    - id: installing-latest-b2-version
      if: inputs.version == 'latest'
      shell: bash
      run: |
        wget -O /usr/local/bin/b2 https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux

    - id: make-b2-executable
      shell: bash
      run: chmod +x /usr/local/bin/b2

    - id: set-credentials
      shell: bash
      if: ${{ env.B2_APPLICATION_KEY_ID && env.B2_APPLICATION_KEY }}
      run: B2_APPLICATION_KEY_ID="${B2_APPLICATION_KEY_ID}" B2_APPLICATION_KEY="${B2_APPLICATION_KEY}" b2 account authorize  

    - id: set-output
      shell: bash
      run: echo "version=$(b2 version)" >> $GITHUB_OUTPUT
